services:
  db:
    image: vaticle/typedb
    container_name: db-typedb
    ports:
      - 1729:1729
    platform: linux/amd64 # DB requested image's platform(linux/amd64)
    volumes: # For Backup
      - ./data:/opt/typedb-all-linux-x86_64/server/data
